// full list

/*
{
    "fullGirlsList":
    [
        "Adventurer",
        "Asian",
        "Aspiration",
        "babee",
        "babie",
        "baby",
        "babyangel",
        "Bby",
        "beau",
        "Beautiful",
        "Bee",
        "bella",
        "Blessed",
        "blossom",
        "champbabe",
        "creativebaby",
        "Dancer",
        "Diva",
        "dreams",
        "EliteBaby",
        "elixir",
        "Female",
        "Fit",
        "Fitness",
        "Forver",
        "FunSize",
        "glucose",
        "highend",
        "highestHeels",
        "hungry",
        "icebaby",
        "Infinite",
        "JetSet",
        "Kat",
        "kbaby",
        "Kiskas",

        "lil",
        "Miss",
        "Miss",
        "Missy",
        "munkee",

        "perfectGirl",
        "Pixie",
        "PrettyInTheCity",
        "Princess",
        "Royalty",
        "Silly",

        "Summertime",
        "Sweet",
        "Sweetheart",
        "sweetsugar",
        "tealPrincess",
        "Thunder",
        "Tight",
        "Tothe9s",
        "treat",
        "Unique",
        "WestCost",
        "Wild",
        "Afrocentric",
        "babe",
        "Babydoll",
        "babygirl",
        "beach",
        "Blondegirl",
        "Blondie",
        "Blunt",
        "Brownzy",
        "Bunnie",
        "champ",
        "chocolat",
        "Contessa",
        "Crimson",
        "downtown",

        "lil",

        "passionate",
        "Promiscious",

        "queen",
        "QUINNtessensual",

        "redehead",
        "Ruby",

        "Smol",
        "SnowBunny",

        "Small Little",
        "Uzername",
        "Wanderlust",
        "xbabyface",
        "xo",
        "xox",
        "xoxxx",
        "xxo",
        "xxoxx",
        "xxx"
    ]
},

        "nouns": [
            "Sugar",
            "SugarBaby",
            "lolita",
            "Melon",
            "Minx",
            "mistress",
            "Eve",
            "goalDigger",
            "GoldDigger",
            "kinkybabe",
            "Sensual",
            "sexpot",

            "Soul",
            "soulareclipse",
            "sugardrop",
            "strawberrry",
            "Red", "Purple",
            "Alitheia",
            "Angel",
            "Cat",
            "Cats",
            "fairy",
            "bee",
            "Diamonds",
            "heels",
            "Mercedes",
            "nymph",
            "EastCoast",
            "Honey",
            "lady"
        ]
    };

*/